import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import MyNavbar from "@/components/MyNavbar";
import { Toaster } from "@/components/ui/toaster";
import { ReduxProvider } from "../redux-toolkit/providers";
// import { Inter as FontSans } from "next/font/google"
// import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <MyNavbar />
          {children}
          <Footer />
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
